"""Render validated agent results into concise GitHub comments."""

from __future__ import annotations

from typing import Any


REQUIRED_RESULT_FIELDS = {
    "summary",
    "evidence",
    "questions",
    "recommended_actions",
    "files_changed",
    "commands_run",
}


def validate_analysis_result(result: dict[str, Any]) -> None:
    missing = REQUIRED_RESULT_FIELDS - result.keys()
    if missing:
        raise ValueError(f"Analysis result is missing fields: {', '.join(sorted(missing))}")
    if not isinstance(result["summary"], str):
        raise ValueError("Analysis result summary must be text.")
    for field in REQUIRED_RESULT_FIELDS - {"summary"}:
        if not isinstance(result[field], list) or not all(
            isinstance(item, str) for item in result[field]
        ):
            raise ValueError(f"Analysis result {field} must be a list of text items.")


def render_documentation_analysis(result: dict[str, Any]) -> str:
    """Render an issue-grooming report without exposing internal execution details."""
    validate_analysis_result(result)
    lines = ["## Doku: documentation analysis", "", result["summary"].strip()]
    _append_section(lines, "Evidence", result["evidence"])
    _append_section(lines, "Questions to resolve", result["questions"])
    _append_section(lines, "Recommended next steps", result["recommended_actions"])
    if result["files_changed"]:
        _append_section(lines, "Documentation files changed", result["files_changed"])
    lines.extend(
        [
            "",
            "_Generated by Doku from the issue, repository workspace, and configured evidence rules. "
            "No GitHub changes were made beyond this comment._",
        ]
    )
    return "\n".join(lines)


def _append_section(lines: list[str], title: str, items: list[str]) -> None:
    if not items:
        return
    lines.extend(["", f"### {title}", ""])
    lines.extend(f"- {item}" for item in items)
