"""Render validated agent results into concise GitHub comments."""

from __future__ import annotations

from typing import Any


REQUIRED_RESULT_FIELDS = {
    "summary",
    "evidence",
    "questions",
    "recommended_actions",
    "files_changed",
    "commands_run",
}
WORKFLOW_STATES = {
    "needs-grooming",
    "needs-decision",
    "needs-documentation",
    "ready-for-development",
    "needs-user-guidance",
}


def validate_analysis_result(result: dict[str, Any]) -> None:
    missing = REQUIRED_RESULT_FIELDS - result.keys()
    if missing:
        raise ValueError(f"Analysis result is missing fields: {', '.join(sorted(missing))}")
    if not isinstance(result["summary"], str):
        raise ValueError("Analysis result summary must be text.")
    for field in REQUIRED_RESULT_FIELDS - {"summary"}:
        if not isinstance(result[field], list) or not all(
            isinstance(item, str) for item in result[field]
        ):
            raise ValueError(f"Analysis result {field} must be a list of text items.")


def render_documentation_analysis(result: dict[str, Any]) -> str:
    """Render an issue-grooming report without exposing internal execution details."""
    validate_analysis_result(result)
    lines = ["## Doku: documentation analysis", "", result["summary"].strip()]
    _append_section(lines, "Evidence", result["evidence"])
    _append_section(lines, "Questions to resolve", result["questions"])
    _append_section(lines, "Recommended next steps", result["recommended_actions"])
    if result["files_changed"]:
        _append_section(lines, "Documentation files changed", result["files_changed"])
    lines.extend(
        [
            "",
            "_Generated by Doku from the issue, repository workspace, and configured evidence rules. "
            "No GitHub changes were made beyond this comment._",
        ]
    )
    return "\n".join(lines)


def validate_orchestration_result(result: dict[str, Any], role: str) -> None:
    """Validate the small result contract used by the polling orchestrator."""
    validate_analysis_result(result)
    next_state = result.get("next_state")
    if next_state not in WORKFLOW_STATES:
        raise ValueError("Orchestrator result next_state must be a supported workflow label.")
    if len(result["questions"]) > 1:
        raise ValueError("An orchestrated agent may ask at most one focused question.")

    if role == "project-owner":
        if next_state == "needs-user-guidance" and len(result["questions"]) != 1:
            raise ValueError(
                "Project Owner must include exactly one focused question for needs-user-guidance."
            )
        if next_state != "needs-user-guidance" and result["questions"]:
            raise ValueError(
                "Project Owner questions must be routed through needs-user-guidance."
            )
    elif role == "documentation":
        if next_state != "needs-decision":
            raise ValueError("Documentation results must return to Project Owner via needs-decision.")
    else:
        raise ValueError(f"Unsupported orchestrated role: {role}")


def render_orchestration_result(
    result: dict[str, Any],
    *,
    role: str,
    source_state: str,
    next_state: str,
    invocation_id: str,
) -> str:
    """Render a validated agent result with durable orchestration metadata."""
    validate_orchestration_result(result, role)
    heading = "Project Owner" if role == "project-owner" else "Doku"
    lines = [
        f"<!-- agent-army:result role={role} invocation={invocation_id} "
        f"from={source_state} next={next_state} -->",
        f"## Agent Army: {heading} completed",
        "",
        "### Decision" if role == "project-owner" else "### Summary",
        "",
        result["summary"].strip(),
        "",
        f"Workflow transition: `{source_state}` → `{next_state}`.",
    ]
    _append_section(lines, "Evidence", result["evidence"])
    _append_section(lines, "Focused question", result["questions"])
    _append_section(lines, "Recommended actions", result["recommended_actions"])
    if result["files_changed"]:
        _append_section(lines, "Files changed", result["files_changed"])
    lines.extend(
        [
            "",
            "_This validated result is the durable record used by the Agent Army polling workflow._",
        ]
    )
    return "\n".join(lines)


def _append_section(lines: list[str], title: str, items: list[str]) -> None:
    if not items:
        return
    lines.extend(["", f"### {title}", ""])
    lines.extend(f"- {item}" for item in items)
